# Generated by Django 2.1.7 on 2019-07-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='강의코드')),
                ('professor', models.CharField(max_length=10, verbose_name='교수님')),
                ('class_room', models.CharField(max_length=15, verbose_name='강의실')),
                ('week', models.CharField(max_length=5, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작시간')),
                ('end_time', models.TimeField(verbose_name='끝나는시간')),
                ('opened_year', models.SmallIntegerField(verbose_name='개설년도')),
                ('opened_semester', models.SmallIntegerField(verbose_name='개설학기')),
                ('opened_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Department', verbose_name='개설학과')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='교과목코드')),
                ('name', models.CharField(max_length=20, verbose_name='교과목명')),
                ('credit', models.FloatField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Area', verbose_name='영역')),
                ('completion_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.CompletionDivision', verbose_name='이수구분')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='대학')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Subject', verbose_name='교과목'),
        ),
    ]
