# Generated by Django 2.1.7 on 2019-07-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='opened_college',
            field=models.CharField(default=1, max_length=50, verbose_name='개설단'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='opened_department',
            field=models.CharField(max_length=50, verbose_name='개설학과'),
        ),
    ]
