# Generated by Django 2.1.7 on 2019-07-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20190718_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='opened_semester',
            field=models.SmallIntegerField(choices=[(10, '1학기'), (20, '2학기'), (11, '여름학기'), (21, '겨울학기')], default=0, verbose_name='개설학기'),
        ),
    ]
