# Generated by Django 2.1.7 on 2019-07-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20190718_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('mon', '월'), ('tue', '화'), ('wed', '수'), ('thu', '목'), ('fir', '금'), ('sat', '토')], max_length=10, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작시간')),
                ('end_time', models.TimeField(verbose_name='끝나는시간')),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='code',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='week',
        ),
        migrations.AddField(
            model_name='lecturetime',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', verbose_name='강의'),
        ),
    ]
