# Generated by Django 2.1.7 on 2019-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20190718_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.CharField(max_length=30, verbose_name='교수님'),
        ),
    ]
