# Generated by Django 2.1.7 on 2019-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20190718_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='class_room',
            field=models.CharField(max_length=40, verbose_name='강의실'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.CharField(max_length=40, verbose_name='교수님'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=40, verbose_name='교과목명'),
        ),
    ]
