# Generated by Django 2.1.7 on 2019-07-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_auto_20190718_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='class_year',
            field=models.SmallIntegerField(default=1, verbose_name='학년'),
            preserve_default=False,
        ),
    ]
