# Generated by Django 2.1.7 on 2019-07-10 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='F', max_length=10, verbose_name='학생성적')),
                ('completion_year', models.SmallIntegerField(verbose_name='이수학년')),
                ('completion_semester', models.SmallIntegerField(verbose_name='이수학기')),
                ('completion_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.CompletionDivision', verbose_name='이수구분')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Subject', verbose_name='과목')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='대학')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
    ]
