# Generated by Django 2.1.7 on 2019-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddedmajor',
            name='major_division',
            field=models.CharField(max_length=20, verbose_name='전공구분'),
        ),
    ]
