# Generated by Django 2.1.7 on 2019-07-12 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190712_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentaddedmajor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo', verbose_name='유저정보'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
