# Generated by Django 2.1.7 on 2019-07-12 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190712_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddedmajor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저정보'),
        ),
    ]
