# Generated by Django 2.1.7 on 2019-07-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190712_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddedmajor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo', verbose_name='유저정보'),
        ),
    ]
