# Generated by Django 2.1.7 on 2019-07-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20190715_2023'),
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegeneral',
            name='university',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='대학'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rulespecific',
            name='university',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='대학'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='university',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='대학'),
            preserve_default=False,
        ),
    ]
