# Generated by Django 2.1.7 on 2019-07-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0003_auto_20190716_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegeneral',
            name='year',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rulespecific',
            name='year',
            field=models.SmallIntegerField(default=0),
        ),
    ]
