# Generated by Django 2.1.7 on 2019-07-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0005_auto_20190717_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulegeneral',
            name='type',
            field=models.IntegerField(choices=[(1, '학점총합'), (2, '과목갯수'), (3, '영역갯수'), (4, '학점평균')], default=1, max_length=20, verbose_name='졸업요건타입'),
        ),
    ]
