# Generated by Django 2.1.7 on 2019-07-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0008_rulespecific_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulegeneral',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '학점총합'), (2, '과목갯수'), (3, '영역갯수'), (4, '학점평균')], default=1, verbose_name='졸업요건타입'),
        ),
        migrations.AlterField(
            model_name='rulespecific',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '학점총합'), (2, '과목갯수'), (3, '영역갯수'), (4, '학점평균')], default=1, verbose_name='졸업요건타입'),
        ),
    ]
