# Generated by Django 2.1.7 on 2019-07-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0009_auto_20190717_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulespecific',
            name='change_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduation.RuleSpecific', verbose_name='특정룰 변경'),
        ),
    ]
