# Generated by Django 2.1.7 on 2019-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='maximum_credit',
            field=models.FloatField(choices=[(4.5, '4.5'), (4.3, '4.3'), (4.0, '4.0')], default=4.5, verbose_name='최대학점'),
        ),
    ]
