# Generated by Django 2.1.7 on 2019-07-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20190715_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completiondivision',
            name='group_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='그룹이름'),
        ),
    ]
