# Generated by Django 2.1.7 on 2019-07-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20190717_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, verbose_name='약어'),
        ),
        migrations.AddField(
            model_name='completiondivision',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, verbose_name='약어'),
        ),
        migrations.AlterField(
            model_name='completiondivision',
            name='name',
            field=models.CharField(max_length=10, verbose_name='이수구분이름'),
        ),
    ]
